[package]
name = "cpid1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
tokio-stream = "0.1.12"
libc = "0.2"
nix = "0.26.2"
